#login
POST http://localhost:8080/login
Content-Type: application/json

{
	"name" : "lorenz",
	"password" : "123"
}

---

#register
POST http://localhost:8080/register
Content-Type: application/json

{
	"name":"lorenz",
	"password":"123",
	"notice":"gib money",
	"tags":["kaffee", "alk"]
}

---

#update user, requires session
POST http://localhost:8080/update
Content-Type: application/json

{
	"notice" : "gib more money",
	"tags" : ["money", "silver", "gold"]
}

---

#get user, requires session
GET http://localhost:8080/user

#reset
GET http://localhost:8080/reset
Content-Type: application/json
Authorization: superdupersupersecrettoken


#play
GET http://localhost:8080/play
Content-Type: application/json
Authorization: superdupersupersecrettoken



